name: tests

on: push

env:
  POSTGRES_USER: mychef
  POSTGRES_PASSWORD: mychef
  POSTGRES_DB: mychef_db
  POSTGRES_HOST: db

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download model
        run: make download
      - name: Build images
        run: make build
      - name: Push images
        run: make push
      - name: Run tests
        run: docker-compose run -T api pytest tests
